Repository AY2425S1-CS2103T-F08-3/tp, pull requests merged in 2024-11, with the labels that each got.

#130 Update UG with editm and deletem commands
  docs/UserGuide.md
Labels: priority.High

#135 Update SampleDataUtil
  src/main/java/seedu/address/model/util/SampleDataUtil.java
Labels: priority.High, severity.Medium

#136 Fix bugs and add test cases for deletem
  src/main/java/seedu/address/logic/commands/DeleteMeetingCommand.java
  src/main/java/seedu/address/logic/commands/EditCommand.java
  src/main/java/seedu/address/model/AddressBook.java
  src/main/java/seedu/address/model/person/Meetings.java
  src/test/java/seedu/address/logic/commands/DeleteMeetingCommandTest.java
  src/test/java/seedu/address/logic/parser/DeleteMeetingCommandParserTest.java
Labels: priority.High

#141 Edit UML Diagrams for DG
  docs/DeveloperGuide.md
  docs/diagrams/ModelClassDiagram.puml
  docs/diagrams/StorageClassDiagram.puml
Labels: priority.High

#142 Update user guide with warnings and sequence diagram
  docs/UserGuide.md
  docs/diagrams/DeleteMeetingSequenceDiagram.puml
Labels: priority.High

#220 Fix Bugs
  src/main/java/seedu/address/logic/commands/ScheduleCommand.java
  src/test/java/seedu/address/logic/commands/ScheduleCommandIntegrationTest.java
Labels: planned.Enhancements, can.close

#223 Dg fixes
  docs/DeveloperGuide.md
  docs/diagrams/ModelClassDiagram.puml
  docs/images/Ui_parts.png
Labels: priority.High

#231 Fix bugs in UG and DG
  docs/DeveloperGuide.md
  docs/UserGuide.md
Labels: severity.Low, UG, DG
